# Generated by Django 4.2.7 on 2024-02-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('faculty_email', models.EmailField(max_length=100)),
                ('faculty_phone', models.CharField(max_length=10)),
                ('is_hod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('instiId', models.FileField(upload_to='documents/')),
                ('letter', models.FileField(upload_to='documents/')),
                ('status', models.CharField(default='Pending Faculty Approval', max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
